### ISSUE TITLE
数据ITEM如果长度变长没有适配吧？

### ISSUE THREAD

**Issue by xiaojiebudai** [huzenan/EasyPickerView#2]
我把数据改成年，4位长度，效果不是很好

**Comment by Carbenson** [comment]
contentWidth = (int) ((maxTextWidth + getPaddingLeft() + getPaddingRight()) * textMaxScale);
120行，乘以最大宽度倍数

**Comment by xiaojiebudai** [comment]
是，我也看到了缩放的倍数问题

**Comment by xiaojiebudai** [comment]
contentWidth = (int) (maxTextWidth* textMaxScale + getPaddingLeft() + getPaddingRight());
应该是这样的吧？

**Comment by Carbenson** [comment]
对，应该是这样的
