### ISSUE TITLE
计算宽度有问题

### ISSUE THREAD

**Issue by Carbenson** [huzenan/EasyPickerView#3]
目前计算的宽度是以未选中的文字为准的
第120行，计算contentWidth的时候，应该乘以textMaxScale，不然选中的文字的两边超过为选中文字的部分就被挡住了，
 eg：contentWidth = (int) (maxTextWidth* textMaxScale + getPaddingLeft() + getPaddingRight());

**Comment by huzenan** [comment]
感谢提醒，确实是这样的，已经修复。
