### ISSUE TITLE
控件不可见 是textMaxScale =1.0导致的吗

### ISSUE THREAD

**Issue by lcqbug** [huzenan/EasyPickerView#4]
如果 wrapcontent 情况下, textMaxScale =1.0,那么控价无法显示? 项目中的 otherActivity 是无法显示的. 具体原因是因为xml文件中 textMaxScale 这个属性没设置正确的原因吗?还是其他?

**Comment by huzenan** [comment]
哈，刚好发现了这个，是的计算有些问题，3q，已经修复了。
