### ISSUE TITLE
更改了数字的大小和宽高后，moveTo()好像就不准确了（比如moveTo(20)，结果在9的位置），这个怎么解决？

### ISSUE THREAD

**Issue by o0yangyang0o** [huzenan/EasyPickerView#5]

**Comment by jacknonebug** [comment]
我也遇到同样的问题,moveTo(20) 到不了DataList中20的位置

**Comment by huzenan** [comment]
可以描述下具体如何更改不？
还有moveTo的参数是下标，看看是不是这里看错了。

**Comment by yingka** [comment]
@huzenan 
epvH = (EasyPickerView) findViewById(R.id.epv_h);
        final ArrayList<String> hDataList = new ArrayList<>();
        for (int i = 0; i < 24; i++)
            hDataList.add("" + i);

        epvH.setDataList(hDataList);

        int index = Integer.parseInt("20");
        epvH.moveTo(index);
设置完数据源后，调用moveTo，这样写本来是想定位到20，但是却定位到的不是20

**Comment by huzenan** [comment]
这个问题是文字高度计算位置导致的，已经修复了，非常感谢反馈！
